version: "3"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"
    tty: true

  nginx:
        container_name: "nginx"
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - "app"
