version: "3"

services:

  nginx:
    container_name: "nginx"
    build: ./nginx
    ports:
        - "80:80"
    depends_on:
        - "app"

  app:
    depends_on:
      - db
    build:
      context: ./go
      dockerfile: ./Dockerfile
    volumes:
      - ./go/app:/go/src/app
    ports:
      - "8080:8080"
    environment:
      - CORS=http://localhost:4200
      - DATABASE_URL=postgresql://postgres:5432/app_db?user=app_user&password=app_password&sslmode=disable
    tty: true

  db:
    container_name: postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=app_db
