DELETE FROM NEAREST_STATION_TB;
INSERT INTO NEAREST_STATION_TB VALUES(1, 7, 1);
INSERT INTO NEAREST_STATION_TB VALUES(2, 6, 5);
INSERT INTO NEAREST_STATION_TB VALUES(3, 2, 1);
INSERT INTO NEAREST_STATION_TB VALUES(4, 8, 3);
INSERT INTO NEAREST_STATION_TB VALUES(5, 9, 5);